/* Generated by Yosys 0.20+1 (git sha1 60a787fa500, clang  -fPIC -Os) */

(* top =  1  *)
(* src = "iiitb_4bbc.v:1.1-33.10" *)
module iiitb_4bbc(Clk, reset, UpOrDown, Count);
  (* src = "iiitb_4bbc.v:16.6-31.9" *)
  wire [3:0] _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  (* src = "iiitb_4bbc.v:10.11-10.14" *)
  input Clk;
  wire Clk;
  (* init = 4'h0 *)
  (* src = "iiitb_4bbc.v:12.20-12.25" *)
  output [3:0] Count;
  wire [3:0] Count;
  (* src = "iiitb_4bbc.v:10.21-10.29" *)
  input UpOrDown;
  wire UpOrDown;
  (* src = "iiitb_4bbc.v:10.15-10.20" *)
  input reset;
  wire reset;
  sky130_fd_sc_hd__clkinv_1 _11_ (
    .A(Count[0]),
    .Y(_00_[0])
  );
  sky130_fd_sc_hd__clkinv_1 _12_ (
    .A(reset),
    .Y(_01_)
  );
  sky130_fd_sc_hd__and3_1 _13_ (
    .A(Count[0]),
    .B(Count[1]),
    .C(UpOrDown),
    .X(_05_)
  );
  sky130_fd_sc_hd__nor3_1 _14_ (
    .A(Count[0]),
    .B(Count[1]),
    .C(UpOrDown),
    .Y(_06_)
  );
  sky130_fd_sc_hd__maj3_1 _15_ (
    .A(Count[0]),
    .B(Count[1]),
    .C(UpOrDown),
    .X(_07_)
  );
  sky130_fd_sc_hd__nor2_1 _16_ (
    .A(_06_),
    .B(_07_),
    .Y(_08_)
  );
  sky130_fd_sc_hd__nor2_1 _17_ (
    .A(_05_),
    .B(_08_),
    .Y(_00_[1])
  );
  sky130_fd_sc_hd__nor2_1 _18_ (
    .A(_05_),
    .B(_06_),
    .Y(_09_)
  );
  sky130_fd_sc_hd__xnor2_1 _19_ (
    .A(Count[2]),
    .B(_09_),
    .Y(_00_[2])
  );
  sky130_fd_sc_hd__mux2i_1 _20_ (
    .A0(_06_),
    .A1(_05_),
    .S(Count[2]),
    .Y(_10_)
  );
  sky130_fd_sc_hd__xnor2_1 _21_ (
    .A(Count[3]),
    .B(_10_),
    .Y(_00_[3])
  );
  sky130_fd_sc_hd__clkinv_1 _22_ (
    .A(reset),
    .Y(_02_)
  );
  sky130_fd_sc_hd__clkinv_1 _23_ (
    .A(reset),
    .Y(_03_)
  );
  sky130_fd_sc_hd__clkinv_1 _24_ (
    .A(reset),
    .Y(_04_)
  );
  (* src = "iiitb_4bbc.v:16.6-31.9" *)
  sky130_fd_sc_hd__dfrtp_1 _25_ (
    .CLK(Clk),
    .D(_00_[0]),
    .Q(Count[0]),
    .RESET_B(_01_)
  );
  (* src = "iiitb_4bbc.v:16.6-31.9" *)
  sky130_fd_sc_hd__dfrtp_1 _26_ (
    .CLK(Clk),
    .D(_00_[1]),
    .Q(Count[1]),
    .RESET_B(_02_)
  );
  (* src = "iiitb_4bbc.v:16.6-31.9" *)
  sky130_fd_sc_hd__dfrtp_1 _27_ (
    .CLK(Clk),
    .D(_00_[2]),
    .Q(Count[2]),
    .RESET_B(_03_)
  );
  (* src = "iiitb_4bbc.v:16.6-31.9" *)
  sky130_fd_sc_hd__dfrtp_1 _28_ (
    .CLK(Clk),
    .D(_00_[3]),
    .Q(Count[3]),
    .RESET_B(_04_)
  );
endmodule
